engines:
  pep8:
    enabled: true
  radon:
    enabled: true
  fixme:
    enabled: true
  eslint:
    enabled: true

ratings:
  paths:
  - plenario/**
  - "**.js"
  - "**.py"
exclude_paths:
- plenario/alembic/**
- plenario/static/js/*