language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests tests/points

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp tests/settings.py.test plenario/settings.py
  - psql -c 'create database plenario_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d plenario_test