language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests tests

addons:
  postgresql: "9.4"

services:
  - postgresql

before_script:
  - cp tests/settings.py.test plenario/settings.py
  - sudo mv /etc/apt/sources.list.d/pgdg-source.list* /tmp
  - sudo apt-get -qq remove postgis
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgis gdal-bin
  - psql -c 'create database plenario_test;' -U postgres
  - psql -c 'create extension postgis;' -U postgres -d plenario_test